/**
 * Scenes that have artwork in public/scenes/.
 *
 * Generated by `npm run scenes`, which scans the folder, optimises anything it
 * finds and rewrites this list. Do not edit the array by hand — the script is
 * the source of truth, so a file that was deleted or misnamed cannot leave a
 * stale entry behind pointing at a 404.
 */

// scenes:begin
export const scenesWithPhotos: string[] = [];
// scenes:end

const photoSet = new Set(scenesWithPhotos);

export function hasScenePhoto(sceneId: string): boolean {
  return photoSet.has(sceneId);
}

export function scenePhotoPath(sceneId: string): string {
  return `/scenes/${sceneId}.jpg`;
}
