import type { AccessoryCategory, AccessoryProduct } from "./types";

export const accessoryCategories: Array<{ id: "all" | AccessoryCategory; label: string }> = [
  { id: "all", label: "All" },
  { id: "pov", label: "POV" },
  { id: "water", label: "Water" },
  { id: "travel", label: "Travel" },
  { id: "vehicle", label: "Vehicle" },
  { id: "sports", label: "Sports" },
  { id: "everyday", label: "Everyday" },
  { id: "mounts", label: "Mounts" },
];

// Customer-safe catalog data. Supplier names, Alibaba links and internal costs
// intentionally live in sourcing.ts so they never enter the public client bundle.
export const accessoryProducts: AccessoryProduct[] = [
  {
    id: "floating-camera-grip",
    slug: "floating-camera-grip",
    name: "Floating Camera Grip",
    shortName: "Floating Grip",
    description: "A bright, buoyant handheld grip for filming in and around water.",
    category: "water",
    useCases: ["Fishing", "Boating", "Kayaking", "Swimming", "Snorkeling"],
    universal: true,
    mountStandard: "Standard action-camera three-prong mount",
    brandsSupported: ["GoPro", "DJI Osmo Action", "Insta360 Ace"],
    compatibilityNote: "Requires the standard action-camera adapter appropriate for the camera.",
    includedItems: ["Floating grip", "Wrist strap", "Mounting screw"],
    warnings: ["Confirm the grip remains buoyant with the complete camera setup before entering deep water."],
    material: "ABS",
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["fishing", "boating", "beach", "ocean", "surfing", "underwater"],
    recommendationMounts: ["handheld", "boat"],
    recommendationReason: "Keeps a handheld camera easier to control and recover around water.",
  },
  {
    id: "quick-release-chest-strap",
    slug: "quick-release-chest-strap",
    name: "Quick-Release Chest Strap",
    shortName: "Chest Strap",
    description: "A washable vest-style harness for steadier hands-free point-of-view footage.",
    category: "pov",
    useCases: ["Fishing", "Cycling", "Hiking", "Skiing", "Motorcycles"],
    universal: true,
    mountStandard: "Standard action-camera mount adapter",
    brandsSupported: ["GoPro", "Other cameras using a GoPro-style adapter"],
    compatibilityNote: "The supplier specifies GoPro and other action cameras; camera-specific adapters still need checking.",
    includedItems: ["Chest strap", "Quick-release camera adapter"],
    warnings: ["Do not wear where the mount could create an impact hazard."],
    material: "Nylon",
    retailPriceUsd: null,
    catalogStatus: "future-bulk",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["fishing", "cycling", "hiking", "skiing", "motorcycle", "running"],
    recommendationMounts: ["chest"],
    recommendationReason: "Gives a stable, hands-free point of view when both hands need to stay on the activity.",
  },
  {
    id: "aluminum-extension-pole",
    slug: "aluminum-extension-pole",
    name: "1.2m Aluminum Extension Pole",
    shortName: "Extension Pole",
    description: "A lightweight telescoping pole for wider travel, group and follow shots.",
    category: "travel",
    useCases: ["Travel", "Vlogging", "Family", "Walking tours", "360 video"],
    universal: false,
    mountStandard: "Camera-dependent adapter",
    brandsSupported: ["GoPro", "DJI Osmo Action", "Insta360"],
    compatibilityNote: "Use only after confirming the supplied thread or adapter for the exact camera.",
    includedItems: ["1.2m telescoping pole"],
    warnings: ["Keep extended poles clear of roads, power lines, rides and other people."],
    material: "Aluminum",
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["walking-tour", "city", "airport", "family", "vlog", "fake-drone"],
    recommendationMounts: ["selfie", "selfie-stick", "stick-360", "handheld"],
    recommendationReason: "Adds reach for travel, group and follow shots without adding a full tripod.",
  },
  {
    id: "backpack-strap-clip",
    slug: "backpack-strap-clip",
    name: "Locking Backpack Strap Clip",
    shortName: "Backpack Clip",
    description: "A quick-release shoulder-strap clip for accessible, hands-free travel footage.",
    category: "travel",
    useCases: ["Travel", "Hiking", "Fishing", "Walking", "Everyday carry"],
    universal: false,
    mountStandard: "Supplier quick-release system",
    brandsSupported: ["GoPro", "DJI", "Insta360 GO", "Insta360 Ace"],
    compatibilityNote: "The supplier lists specific camera families; verify the included adapter before ordering.",
    includedItems: ["Backpack strap clip", "Quick-release camera plate"],
    warnings: ["Use a separate safety tether where a dropped camera could be lost."],
    material: "PC, TPU, carbon steel and stainless steel",
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["hiking", "walking-tour", "city", "airport", "fishing"],
    recommendationMounts: ["handheld", "unknown"],
    recommendationReason: "Keeps the camera ready without occupying a hand during travel or hiking.",
  },
  {
    id: "handlebar-pole-clamp",
    slug: "handlebar-pole-clamp",
    name: "Handlebar + Pole Clamp",
    shortName: "Pole Clamp",
    description: "An adjustable clamp for handlebars, rails and round poles from 9–23mm.",
    category: "vehicle",
    useCases: ["Cycling", "Motorcycles", "Boat rails", "Fishing rails", "ATVs"],
    universal: false,
    mountStandard: "1/4\"-20 camera interface",
    brandsSupported: ["Cameras or adapters with a 1/4\"-20 thread"],
    compatibilityNote: "Camera and action-camera adapter must provide a matching 1/4\"-20 thread.",
    includedItems: ["Pole clamp", "Ball-joint camera mount", "Thickening pad"],
    warnings: ["Check clamp torque and add a safety tether before use on moving vehicles."],
    material: "Plastic mount body with metal hardware",
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["cycling", "motorcycle", "boating", "fishing", "road-trip"],
    recommendationMounts: ["handlebar", "boat", "vehicle"],
    recommendationReason: "Secures the camera to a round bar when a fixed point of view is genuinely useful.",
  },
  {
    id: "suction-cup-mount",
    slug: "suction-cup-mount",
    name: "Adjustable Suction Cup Mount",
    shortName: "Suction Mount",
    description: "A compact adjustable mount for clean glass and other smooth surfaces.",
    category: "vehicle",
    useCases: ["Cars", "Windows", "Static glass", "Smooth surfaces"],
    universal: false,
    mountStandard: "Supplier camera adapter",
    brandsSupported: ["Action cameras", "Smartphones", "GPS devices"],
    compatibilityNote: "Confirm the included camera adapter and the permitted mounting surface before use.",
    includedItems: ["Suction mount", "Camera adapter"],
    warnings: ["Never rely on suction alone where detachment could injure someone; clean the surface and use a tether."],
    material: "ABS and silicone",
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["road-trip", "boating", "motorsports"],
    recommendationMounts: ["vehicle"],
    recommendationReason: "Provides a repeatable fixed angle on a suitable smooth surface.",
  },
  {
    id: "universal-adapter-kit",
    slug: "universal-adapter-kit",
    name: "9-in-1 Mount Adapter Kit",
    shortName: "Adapter Kit",
    description: "A small bridge kit for moving between common action-camera and 1/4-inch mounts.",
    category: "mounts",
    useCases: ["Mixed camera bags", "Tripods", "Quick release", "Replacement hardware"],
    universal: true,
    mountStandard: "GoPro-style mount and 1/4\" camera adapter",
    brandsSupported: ["GoPro", "Insta360", "Compatible action cameras"],
    compatibilityNote: "Choose the correct adapter from the pack for the camera and receiving mount.",
    includedItems: ["1/4\" adapter", "Thumb screw", "J-hook buckle", "Assorted mounting hardware"],
    warnings: ["Inspect plastic buckles and threaded parts before high-vibration use."],
    material: "Plastic and metal hardware",
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: [],
    recommendationMounts: ["tripod", "handlebar", "vehicle", "boat", "unknown"],
    recommendationReason: "Solves a real compatibility gap when the selected camera and support use different common mounts.",
  },
  {
    id: "safety-tether-kit",
    slug: "safety-tether-kit",
    name: "Adhesive Safety Tether Kit",
    shortName: "Safety Tether",
    description: "A lightweight secondary retention point for higher-risk mounts and environments.",
    category: "mounts",
    useCases: ["Boats", "Fishing", "Motorcycles", "Kayaking", "Skiing", "Vehicles"],
    universal: true,
    mountStandard: "Adhesive anchor and tether loop",
    brandsSupported: ["GoPro", "Other action cameras"],
    compatibilityNote: "The tether attaches to a suitable camera or housing loop; surface preparation is essential.",
    includedItems: ["Adhesive anchor", "Safety tether"],
    warnings: ["A tether is secondary retention, not a substitute for a correctly installed primary mount."],
    material: "ABS and adhesive pad",
    retailPriceUsd: null,
    catalogStatus: "future-bulk",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["fishing", "boating", "ocean", "surfing", "motorcycle", "cycling", "skiing", "road-trip", "underwater"],
    recommendationMounts: ["vehicle", "boat", "handlebar", "helmet"],
    recommendationReason: "Adds secondary retention where a failed mount could mean a lost camera or a hazard.",
  },
  {
    id: "flexible-mini-tripod",
    slug: "flexible-mini-tripod",
    name: "Flexible Mini Tripod",
    shortName: "Flexible Tripod",
    description: "A compact bendable support for railings, branches and uneven tabletop setups.",
    category: "everyday",
    useCases: ["Travel", "Family", "Timelapse", "Talking to camera", "Night shots"],
    universal: false,
    mountStandard: "Camera-dependent adapter",
    brandsSupported: ["GoPro", "DJI", "Insta360", "Smartphones"],
    compatibilityNote: "Confirm the load rating and the exact camera adapter before ordering.",
    includedItems: ["Flexible tripod", "Camera or phone adapter depending on variant"],
    warnings: ["Wrap all legs securely and test the setup close to the ground before elevated use."],
    material: null,
    retailPriceUsd: null,
    catalogStatus: "future-bulk",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["timelapse", "city-lights", "talking-head", "family", "product", "food-video"],
    recommendationMounts: ["tripod", "handheld"],
    recommendationReason: "Creates a stable camera position when a full-size tripod would be impractical.",
  },
  {
    id: "adjustable-head-strap",
    slug: "adjustable-head-strap",
    name: "Adjustable Head Strap",
    shortName: "Head Strap",
    description: "A lightweight elastic head mount for straightforward first-person footage.",
    category: "pov",
    useCases: ["Hiking", "Fishing", "Work demonstrations", "Low-impact POV"],
    universal: false,
    mountStandard: "GoPro-style action-camera mount",
    brandsSupported: ["GoPro", "SJCAM", "Xiaomi Yi"],
    compatibilityNote: "The listing title and detailed compatibility fields disagree about DJI and Insta360; those systems are not claimed here.",
    includedItems: ["Elastic head strap", "Mounting screw"],
    warnings: ["Not for contact sports, driving or any activity where the mount could create an impact hazard."],
    material: "Nylon and polycarbonate",
    retailPriceUsd: null,
    catalogStatus: "future-bulk",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["hiking", "fishing"],
    recommendationMounts: ["head"],
    recommendationReason: "Supports a natural eye-line point of view for low-impact, hands-free filming.",
  },
  {
    id: "magnetic-quick-release-base",
    slug: "magnetic-quick-release-base",
    name: "Magnetic Quick-Release Base",
    shortName: "Magnetic QR Base",
    description:
      "A metal magnetic quick-release base with a dual interface, so the camera snaps between mounts in seconds instead of being unscrewed.",
    category: "mounts",
    useCases: ["Fast mount swaps", "Cycling", "Motorcycles", "Travel", "Everyday carry"],
    universal: false,
    mountStandard: "Magnetic quick-release over the standard three-prong interface",
    brandsSupported: ["DJI Osmo Action", "DJI Osmo Nano", "Insta360 Ace", "Insta360 X5"],
    compatibilityNote:
      "Supplier lists DJI Action 6/6 Pro/5 Pro/4/3 and Osmo Nano plus Insta360 Ace Pro 2/Ace Pro/X5. Compatibility is supplier-claimed — confirm your camera's magnetic latch engages fully before trusting it in motion.",
    includedItems: ["Magnetic quick-release base"],
    warnings: [
      "Magnetic mounts are convenient, not fail-safe — use a tether over water or at speed.",
    ],
    material: "Metal",
    // Owner-approved launch price is $25, recorded in sourcing.ts
    // (recommendedRetailPriceUsd). It becomes the public price when the
    // product flips to "ready" — the validator forbids pricing a product
    // customers cannot buy yet.
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["motorcycle", "cycling", "walking-tour", "road-trip", "hiking", "vlog"],
    recommendationMounts: ["chest", "helmet", "handlebar", "vehicle", "tripod"],
    recommendationReason: "Moves one camera between mounts in seconds — the accessory that makes owning several mounts practical.",
  },
  {
    id: "folding-selfie-tripod",
    slug: "folding-selfie-tripod",
    name: "Folding Selfie Stick Tripod",
    shortName: "Folding Tripod Stick",
    description:
      "A pocketable aluminum selfie stick that unfolds into a tripod — extends to 0.4 m, tilts, and rotates 180 degrees.",
    category: "everyday",
    useCases: ["Vlogging", "Travel", "Talking to camera", "Timelapses", "Group shots"],
    universal: true,
    mountStandard: "Standard action-camera two-claw interface",
    brandsSupported: ["GoPro", "DJI Osmo Action", "Insta360"],
    compatibilityNote:
      "Two-claw interface fits GoPro-style folding fingers directly; supplier lists GoPro Hero 13, Insta360 X5 and DJI Osmo Action 3/4/5 Pro.",
    includedItems: ["Folding selfie stick tripod"],
    warnings: ["Rated for action cameras — not for heavy mirrorless bodies."],
    material: "Aluminum alloy and polycarbonate",
    // Owner-approved launch price is $35, recorded in sourcing.ts; goes public
    // when the product flips to "ready".
    retailPriceUsd: null,
    catalogStatus: "researching",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["vlog", "talking-head", "walking-tour", "timelapse", "family", "tiktok"],
    recommendationMounts: ["handheld", "selfie", "tripod", "selfie-stick"],
    recommendationReason: "One pocketable grip that covers handheld, selfie-stick and tripod shots on a single trip.",
  },
];

export function getAccessory(slug: string) {
  return accessoryProducts.find((product) => product.slug === slug);
}
