import type { AccessoryCategory, AccessoryProduct } from "./types";

export const accessoryCategories: Array<{ id: "all" | AccessoryCategory; label: string }> = [
  { id: "all", label: "All" },
  { id: "pov", label: "POV" },
  { id: "water", label: "Water" },
  { id: "travel", label: "Travel" },
  { id: "vehicle", label: "Vehicle" },
  { id: "sports", label: "Sports" },
  { id: "everyday", label: "Everyday" },
  { id: "mounts", label: "Mounts" },
];

// Customer-safe catalog data. Supplier names, Alibaba links and internal costs
// intentionally live in sourcing.ts so they never enter the public client bundle.
export const accessoryProducts: AccessoryProduct[] = [
  {
    id: "backpack-strap-clip",
    slug: "backpack-strap-clip",
    name: "Locking Backpack Strap Clip",
    shortName: "Backpack Clip",
    description: "A quick-release shoulder-strap clip for accessible, hands-free travel footage.",
    category: "travel",
    useCases: ["Travel", "Hiking", "Fishing", "Walking", "Everyday carry"],
    universal: false,
    mountStandard: "Supplier quick-release system",
    brandsSupported: ["GoPro", "DJI", "Insta360 GO", "Insta360 Ace"],
    compatibilityNote: "The supplier lists specific camera families; verify the included adapter before ordering.",
    includedItems: ["Backpack strap clip", "Quick-release camera plate"],
    warnings: ["Use a separate safety tether where a dropped camera could be lost."],
    material: "PC, TPU, carbon steel and stainless steel",
    retailPriceUsd: 25,
    catalogStatus: "ready",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["hiking", "walking-tour", "city", "airport", "fishing"],
    recommendationMounts: ["handheld", "unknown"],
    recommendationReason: "Keeps the camera ready without occupying a hand during travel or hiking.",
  },
  {
    id: "suction-cup-mount",
    slug: "suction-cup-mount",
    name: "Adjustable Suction Cup Mount",
    shortName: "Suction Mount",
    description: "A compact adjustable mount for clean glass and other smooth surfaces.",
    category: "vehicle",
    useCases: ["Cars", "Windows", "Static glass", "Smooth surfaces"],
    universal: false,
    mountStandard: "Supplier camera adapter",
    brandsSupported: ["Action cameras", "Smartphones", "GPS devices"],
    compatibilityNote: "Confirm the included camera adapter and the permitted mounting surface before use.",
    includedItems: ["Suction mount", "Camera adapter"],
    warnings: ["Never rely on suction alone where detachment could injure someone; clean the surface and use a tether."],
    material: "ABS and silicone",
    retailPriceUsd: 45,
    catalogStatus: "ready",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["road-trip", "boating", "motorsports"],
    recommendationMounts: ["vehicle"],
    recommendationReason: "Provides a repeatable fixed angle on a suitable smooth surface.",
  },
  {
    id: "magnetic-quick-release-base",
    slug: "magnetic-quick-release-base",
    name: "Magnetic Quick-Release Base",
    shortName: "Magnetic QR Base",
    description:
      "A metal magnetic quick-release base with a dual interface, so the camera snaps between mounts in seconds instead of being unscrewed.",
    category: "mounts",
    useCases: ["Fast mount swaps", "Cycling", "Motorcycles", "Travel", "Everyday carry"],
    universal: false,
    mountStandard: "Magnetic quick-release over the standard three-prong interface",
    brandsSupported: ["DJI Osmo Action", "DJI Osmo Nano", "Insta360 Ace", "Insta360 X5"],
    compatibilityNote:
      "Supplier lists DJI Action 6/6 Pro/5 Pro/4/3 and Osmo Nano plus Insta360 Ace Pro 2/Ace Pro/X5. Compatibility is supplier-claimed — confirm your camera's magnetic latch engages fully before trusting it in motion.",
    includedItems: ["Magnetic quick-release base"],
    warnings: [
      "Magnetic mounts are convenient, not fail-safe — use a tether over water or at speed.",
    ],
    material: "Metal",
    // Owner-approved launch price is $25, recorded in sourcing.ts
    // (recommendedRetailPriceUsd). It becomes the public price when the
    // product flips to "ready" — the validator forbids pricing a product
    // customers cannot buy yet.
    retailPriceUsd: 25,
    catalogStatus: "ready",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["motorcycle", "cycling", "walking-tour", "road-trip", "hiking", "vlog"],
    recommendationMounts: ["chest", "helmet", "handlebar", "vehicle", "tripod"],
    recommendationReason: "Moves one camera between mounts in seconds — the accessory that makes owning several mounts practical.",
  },
  {
    id: "folding-selfie-tripod",
    slug: "folding-selfie-tripod",
    name: "Folding Selfie Stick Tripod",
    shortName: "Folding Tripod Stick",
    description:
      "A pocketable aluminum selfie stick that unfolds into a tripod — extends to 0.4 m, tilts, and rotates 180 degrees.",
    category: "everyday",
    useCases: ["Vlogging", "Travel", "Talking to camera", "Timelapses", "Group shots"],
    universal: true,
    mountStandard: "Standard action-camera two-claw interface",
    brandsSupported: ["GoPro", "DJI Osmo Action", "Insta360"],
    compatibilityNote:
      "Two-claw interface fits GoPro-style folding fingers directly; supplier lists GoPro Hero 13, Insta360 X5 and DJI Osmo Action 3/4/5 Pro.",
    includedItems: ["Folding selfie stick tripod"],
    warnings: ["Rated for action cameras — not for heavy mirrorless bodies."],
    material: "Aluminum alloy and polycarbonate",
    // Owner-approved launch price is $35, recorded in sourcing.ts; goes public
    // when the product flips to "ready".
    retailPriceUsd: 35,
    catalogStatus: "ready",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["vlog", "talking-head", "walking-tour", "timelapse", "family", "tiktok"],
    recommendationMounts: ["handheld", "selfie", "tripod", "selfie-stick"],
    recommendationReason: "One pocketable grip that covers handheld, selfie-stick and tripod shots on a single trip.",
  },
  {
    id: "pocket-lens-cover",
    slug: "pocket-lens-cover",
    name: "Pocket Camera Flip Lens Cover",
    shortName: "Pocket Lens Cover",
    description: "A flip-open protective cover that shields a pocket gimbal camera's lens and screen between shots.",
    category: "everyday",
    useCases: ["Travel", "Vlogging", "Everyday carry", "Bag protection"],
    universal: false,
    mountStandard: "Camera-specific fitted cover",
    brandsSupported: ["DJI Osmo Pocket"],
    compatibilityNote: "Supplier lists DJI Osmo Pocket 4 Pro; confirm your exact Pocket model before ordering.",
    includedItems: ["Flip lens/screen cover"],
    warnings: ["A cover protects against scratches and knocks, not drops onto hard ground."],
    material: null,
    // Owner-approved launch price is $35, recorded in sourcing.ts.
    retailPriceUsd: 35,
    catalogStatus: "ready",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["walking-tour", "city", "airport", "road-trip", "vlog"],
    recommendationMounts: ["handheld", "gimbal"],
    recommendationReason: "Pocket gimbals ride unprotected in bags and pockets - this keeps the lens and screen safe between shots.",
  },
  {
    id: "wrist-lanyard",
    slug: "wrist-lanyard",
    name: "Anti-Lost Wrist Lanyard",
    shortName: "Wrist Lanyard",
    description: "An adjustable wrist lanyard that keeps the camera or selfie stick tethered to your hand.",
    category: "everyday",
    useCases: ["Water", "Travel", "Crowds", "Boats", "Heights"],
    universal: true,
    mountStandard: "Loop plus 1/4-20 screw attachment",
    brandsSupported: ["GoPro", "DJI", "Insta360"],
    compatibilityNote: "Supplier lists Insta360 X5, DJI Action 5/4, GoPro Hero and DJI Pocket 3/4; attaches to most grips and sticks.",
    includedItems: ["Adjustable wrist lanyard"],
    warnings: ["A lanyard is drop insurance, not a substitute for a secure mount."],
    material: null,
    // Owner-approved launch price is $10, recorded in sourcing.ts.
    retailPriceUsd: 10,
    catalogStatus: "ready",
    fulfillmentMode: "MANUAL_ALIBABA",
    recommendationSceneIds: ["boating", "beach", "ocean", "theme-park", "city", "hiking"],
    recommendationMounts: ["handheld", "selfie", "selfie-stick"],
    recommendationReason: "The cheapest insurance on the site - one slip over water or a railing pays for it a hundred times over.",
  },
];

export function getAccessory(slug: string) {
  return accessoryProducts.find((product) => product.slug === slug);
}
