import type { AccessorySourcingRecord, SupplierCandidate } from "./types";

const RESEARCH_DATE = "2026-08-15";
const shippingRequiresConfirmation =
  "Shipping requires confirmation for each destination and one-unit checkout; no universal shipping cost is published.";

const candidate = (value: SupplierCandidate) => value;

export const accessorySourcingRecords: AccessorySourcingRecord[] = [
  {
    productId: "floating-camera-grip",
    verificationStatus: "needs-confirmation",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "SHENZHEN HOSHI ELECTRONIC TECHNOLOGY CO., LTD.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Floaty-Bobber-With-Strap-and-Screw_60468845661.html",
      supplierProductId: "60468845661",
      supplierYearsActive: 11,
      supplierRating: null,
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "£0.0669–£1.70",
      actualOneUnitPrice: null,
      samplePrice: null,
      currency: "GBP",
      moq: 1,
      pricingTiers: [{ quantity: "1–1,000,000 units", price: "Displayed range £0.0669–£1.70; exact tier not shown" }],
      shippingFinding: "Shipping fee and delivery date are shown as to be negotiated.",
      deliveryFinding: "Supplier page shows a 3-day lead time for the displayed quantity band; transit time is not published.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Supplier states compatibility with all action cameras.", "Displayed range is not treated as an actual one-unit price."],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "MOQ 1 appears possible; first confirm the exact single-unit variant, delivered cost and buoyancy with a complete camera.",
    selectionReason: "One-piece inquiry is available and the listing explicitly targets water use with action cameras.",
    blockers: ["Exact one-unit tier", shippingRequiresConfirmation, "Reseller image permission", "Physical buoyancy/quality test"],
  },
  {
    productId: "quick-release-chest-strap",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Telesin Digital Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Telesin-New-upgrade-action-camera-mount_1601162241451.html",
      supplierProductId: "1601162241451",
      supplierYearsActive: 12,
      supplierRating: null,
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "$6.10–$6.90",
      actualOneUnitPrice: null,
      samplePrice: "$20.99",
      currency: "USD",
      moq: 10,
      pricingTiers: [
        { quantity: "10–99 units", price: "$6.90" },
        { quantity: "100–499 units", price: "$6.70" },
        { quantity: "500–1,999 units", price: "$6.50" },
        { quantity: "2,000+ units", price: "$6.10" },
      ],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Listing shows 7-day lead time for 1–50 units; delivery transit is not published.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: ["Vest-style washable nylon design with quick-release adapter.", "This is a future-bulk candidate, not a one-at-a-time launch item."],
    })],
    marketComparisons: [{ label: "GoPro Sports Kit (Chesty + pole mount kit)", observedPrice: "$79.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "The $6.90 tier starts at 10 units, but no bulk buy should occur until sales are validated and the harness is physically tested.",
    selectionReason: "The design is closer to the comfortable, quick-release harness requested than the cheapest elastic-only listings.",
    blockers: ["MOQ 10 for normal pricing", shippingRequiresConfirmation, "Dropshipping confirmation", "Reseller image permission", "Physical comfort/retention test"],
  },
  {
    productId: "aluminum-extension-pole",
    verificationStatus: "needs-confirmation",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Hqs Technology Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: "https://hqs.en.alibaba.com",
      alibabaProductUrl: "https://www.alibaba.com/product-detail/1-2M-Aluminum-Lightweight-Extension-Monopod_1601197066642.html",
      supplierProductId: "1601197066642",
      supplierYearsActive: 17,
      supplierRating: "4.5/5.0 (214 supplier reviews shown)",
      supplierVerified: true,
      tradeAssurance: null,
      displayedPrice: "$3.55–$4.50",
      actualOneUnitPrice: null,
      samplePrice: null,
      currency: "USD",
      moq: 1,
      pricingTiers: [{ quantity: "1+ piece", price: "Displayed range $3.55–$4.50; selected variant price requires checkout" }],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Dispatch/transit for one unit requires checkout confirmation.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Alibaba search listing showed 381 sold.", "Exact adapter/variant needs to be confirmed before claiming broad compatibility."],
    })],
    marketComparisons: [
      { label: "GoPro 1.2m Extension Pole + Waterproof Shutter Remote", observedPrice: "$99.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE },
      { label: "GoPro 3-Way 2.0", observedPrice: "$79.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE },
    ],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "MOQ 1 supports validation; store higher-quantity tiers only after the selected variant is confirmed.",
    selectionReason: "One-piece availability, established supplier history and strong transaction signal make it worth a sample check.",
    blockers: ["Exact one-unit variant price", shippingRequiresConfirmation, "Adapter contents", "Reseller image permission", "Physical flex/load test"],
  },
  {
    productId: "backpack-strap-clip",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Should-Strap-Mount-Quick-Release-Adapter_1601440655582.html",
      supplierProductId: "1601440655582",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 177.90 (~US$5.41) at the 5-299 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 338.85 (~US$10.30)",
      currency: "THB",
      moq: 5,
      pricingTiers: [
        { quantity: "5-299 pieces", price: "THB 177.90 (~US$5.41)" },
        { quantity: "300-1,999 pieces", price: "THB 172.82 (~US$5.25)" },
        { quantity: "2,000-5,999 pieces", price: "THB 169.43 (~US$5.15)" },
        { quantity: "6,000+ pieces", price: "THB 160.96 (~US$4.89)" },
      ],
      shippingFinding: "Supplier-to-owner shipping THB 434.06 (~US$13.20) for 5 pieces, ~US$2.64/unit, to a Thailand address on Aug 16. Outbound customer shipping absorbed in the owner-approved $25 price; 0.07 kg package.",
      deliveryFinding: "Guaranteed delivery Aug 25 - Sep 20 quoted Aug 16.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner-picked supplier (same company as launch products 1-3); browsed via the owner's session 2026-08-16, THB display ~33 THB/USD.",
        "Photo permission owner-confirmed for this supplier 2026-08-16.",
        "Variant on page: For DJI Osmo Action 3/4/5 Pro anti-slip backpack shoulder-strap bracket; 38 sold, no product reviews yet.",
        "Owner-approved launch price: US$25 (2026-08-16).",
        "13x7x10 cm packaging.",
      ],
    }), candidate({
      role: "alternative",
      supplierName: "Shenzhen Telesin Digital Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Telesin-Universal-Backpack-Clip-for-Go-1600974761579.html",
      supplierProductId: "1600974761579",
      supplierYearsActive: 12,
      supplierRating: "4.9/5.0 (522 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "B/.3.50–B/.4.00",
      actualOneUnitPrice: null,
      samplePrice: "B/.12.90",
      currency: "PAB",
      moq: 10,
      pricingTiers: [
        { quantity: "10–49 units", price: "B/.4.00" },
        { quantity: "50–499 units", price: "B/.3.80" },
        { quantity: "500+ units", price: "B/.3.50" },
      ],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Listing shows 8-day lead time for 1–50 units; transit is not published.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: ["Supplier lists max supported camera weight as 250g.", "Materials listed: PC, TPU, carbon steel and 316 stainless steel."],
    })],
    marketComparisons: [{ label: "GoPro Magnetic Swivel Clip", observedPrice: "$34.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: 8.05,
    recommendedRetailPriceUsd: 25,
    estimatedProfitUsd: 11.42,
    estimatedMarginPercent: 46,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "MOQ 10 and a sample price make this a later candidate unless the supplier confirms one-piece fulfillment.",
    selectionReason: "The specified locking clip and multi-material construction better match the quality brief than a bare spring clip.",
    blockers: ["MOQ 10", shippingRequiresConfirmation, "Dropshipping confirmation", "Reseller image permission", "Physical lock/strap test"],
  },
  {
    productId: "handlebar-pole-clamp",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Smilin Electronic Technology Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Portable-Adjustable-Pipe-Clip-Pole-Clamp_60832929114.html",
      supplierProductId: "60832929114",
      supplierYearsActive: 15,
      supplierRating: null,
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "£0.6366–£1.39",
      actualOneUnitPrice: "£1.39 for the 1–99 piece tier",
      samplePrice: null,
      currency: "GBP",
      moq: 1,
      pricingTiers: [
        { quantity: "1–99 pieces", price: "£1.39" },
        { quantity: "100–999 pieces", price: "£1.13" },
        { quantity: "1,000–9,999 pieces", price: "£0.8987" },
        { quantity: "10,000+ pieces", price: "£0.6366" },
      ],
      shippingFinding: "Shipping total is shown as to be negotiated.",
      deliveryFinding: "Delivery timing is not published for one unit.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Supplier specifies a 9–23mm handlebar range with thickening pad and a 1/4\"-20 interface."],
    })],
    marketComparisons: [{ label: "GoPro Handlebar / Seatpost / Pole Mount", observedPrice: "$39.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "MOQ 1 supports validation; the first meaningful published discount starts at 100 pieces.",
    selectionReason: "It publishes the actual clamp diameter range and 1/4\"-20 interface instead of making a vague universal claim.",
    blockers: [shippingRequiresConfirmation, "Dropshipping confirmation", "Reseller image permission", "Physical vibration/torque test"],
  },
  {
    productId: "suction-cup-mount",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Suction-Cup-Camera-Car-Mount-for_1601905939661.html",
      supplierProductId: "1601905939661",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 237.20 (≈US$7.21) at the 10–199 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 338.85 (≈US$10.30)",
      currency: "THB",
      moq: 10,
      pricingTiers: [
        { quantity: "10–199 pieces", price: "THB 237.20 (≈US$7.21)" },
        { quantity: "200–1,999 pieces", price: "THB 228.72 (≈US$6.95)" },
        { quantity: "2,000–4,999 pieces", price: "THB 220.25 (≈US$6.70)" },
        { quantity: "≥5,000 pieces", price: "THB 211.78 (≈US$6.44)" },
      ],
      shippingFinding: "FREE supplier-to-owner shipping shown (capped THB 677.69 on THB 1,016.54+ orders) to a Thailand address on Aug 16.",
      deliveryFinding: "Guaranteed delivery Aug 25–Sep 20 quoted Aug 16.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner-picked supplier (same company as launch products #1 and #2); browsed through the owner's session 2026-08-16, THB display ≈33 THB/USD.",
        "Photo permission owner-confirmed for this supplier 2026-08-16.",
        "1/4\"-20 screw mount with 360° rotation and quick release; 15x9x10 cm, 0.16 kg.",
        "No product reviews shown; suction retention on a windshield is the critical physical test before launch.",
        "Owner-approved launch price: US$45 (2026-08-16).",
      ],
    }), candidate({
      role: "alternative",
      supplierName: "Hangzhou Superb Imp. & Exp. Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Action-Camera-Car-Suction-Cup-Mount_1600165629792.html",
      supplierProductId: "1600165629792",
      supplierYearsActive: 9,
      supplierRating: "4.8/5.0 (265 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "CA$0.6695–CA$0.7671",
      actualOneUnitPrice: "CA$0.7671 for the 1–9 piece tier",
      samplePrice: null,
      currency: "CAD",
      moq: 1,
      pricingTiers: [
        { quantity: "1–9 pieces", price: "CA$0.7671" },
        { quantity: "10–99 pieces", price: "CA$0.7253" },
        { quantity: "100–999 pieces", price: "CA$0.6974" },
        { quantity: "1,000+ pieces", price: "CA$0.6695" },
      ],
      shippingFinding: "Shipping fee and delivery date are shown as to be negotiated.",
      deliveryFinding: "Transit time requires supplier confirmation.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Listing states ABS/silicone construction, 70g weight and a one-year warranty.", "The price is unusually low; launch requires a physical suction and retention test."],
    })],
    marketComparisons: [{ label: "GoPro Suction Cup", observedPrice: "$39.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: 7.21,
    recommendedRetailPriceUsd: 45,
    estimatedProfitUsd: 31.18,
    estimatedMarginPercent: 69,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "MOQ 1 is suitable for a sample; do not bulk-buy a safety-critical suction product before testing.",
    selectionReason: "One-piece tier, stated material and warranty make it researchable, but not yet safe to sell without a test.",
    blockers: [shippingRequiresConfirmation, "Dropshipping confirmation", "Reseller image permission", "Physical suction/heat/vibration test"],
  },
  {
    productId: "universal-adapter-kit",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Kasin Technology Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: "https://kasin.en.alibaba.com",
      alibabaProductUrl: "https://www.alibaba.com/product-detail/9-in-1-Kit-1-4_1600941674794.html",
      supplierProductId: "1600941674794",
      supplierYearsActive: 7,
      supplierRating: "4.7/5.0 (17 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "$0.58–$2.15",
      actualOneUnitPrice: null,
      samplePrice: null,
      currency: "USD",
      moq: 1,
      pricingTiers: [{ quantity: "1 pack", price: "Displayed range $0.58–$2.15; exact pack variant requires checkout" }],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "One-pack delivery timing requires checkout confirmation.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Listing title specifies a 1/4\" adapter, thumb screw, J-hook buckle and GoPro/Insta360 use."],
    })],
    marketComparisons: [
      { label: "GoPro Tripod Mounts", observedPrice: "$19.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE },
      { label: "GoPro Tripod Adapters", observedPrice: "$29.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE },
    ],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "MOQ 1 supports validation; pack contents and the one-pack variant must be confirmed before retail pricing.",
    selectionReason: "It directly addresses the common GoPro-style to 1/4-inch compatibility gap in a small pack.",
    blockers: ["Exact one-pack variant price", shippingRequiresConfirmation, "Pack contents", "Reseller image permission", "Physical buckle/thread test"],
  },
  {
    productId: "safety-tether-kit",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Hqs Technology Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/For-GoPro-Accessories-Safety-Insurance-Tether_1601047750164.html",
      supplierProductId: "1601047750164",
      supplierYearsActive: 17,
      supplierRating: "4.5/5.0 (533 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "$0.25",
      actualOneUnitPrice: null,
      samplePrice: "$0.25 shown",
      currency: "USD",
      moq: 100,
      pricingTiers: [{ quantity: "100+ pieces", price: "$0.25 displayed" }],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Listing shows 7-day lead time for 1–10 pieces, despite a stated MOQ of 100; supplier confirmation is required.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: ["ABS plus adhesive pad; supplier states GoPro and other action-camera use.", "MOQ and sample display are internally inconsistent."],
    })],
    marketComparisons: [{ label: "GoPro Curved + Flat Adhesive Mounts", observedPrice: "$19.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "Potential low-cost multi-pack only after demand and adhesive quality are proven; not valid for manual one-at-a-time ordering today.",
    selectionReason: "The product is useful and simple, but the current listing belongs in the future-bulk queue rather than launch checkout.",
    blockers: ["MOQ 100", "Listing quantity inconsistency", shippingRequiresConfirmation, "Adhesive provenance and physical test", "Reseller image permission"],
  },
  {
    productId: "flexible-mini-tripod",
    verificationStatus: "needs-confirmation",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Telesin Digital Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: "https://telesin.en.alibaba.com",
      alibabaProductUrl: "https://www.alibaba.com/product-detail/TELESIN-camera-accessories-for-gopro-dji_1601029996601.html",
      supplierProductId: "1601029996601",
      supplierYearsActive: 13,
      supplierRating: "4.8/5.0 (27 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "$4.70–$5.20",
      actualOneUnitPrice: null,
      samplePrice: null,
      currency: "USD",
      moq: 10,
      pricingTiers: [{ quantity: "10+ units", price: "Displayed range $4.70–$5.20" }],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Delivery timing requires checkout or supplier confirmation.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Listing title names GoPro, DJI, Insta360, action cameras and phones.", "Load rating and exact included adapter were not exposed in the searchable source."],
    })],
    marketComparisons: [{ label: "GoPro Gooseneck flexible camera mount", observedPrice: "$19.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "MOQ 10 makes this a later candidate unless a sample or one-piece fulfillment path is confirmed.",
    selectionReason: "A known accessory supplier and multi-ecosystem listing make it worth further verification.",
    blockers: ["MOQ 10", "Load rating", "Adapter contents", shippingRequiresConfirmation, "Physical grip/fatigue test", "Reseller image permission"],
  },
  {
    productId: "adjustable-head-strap",
    verificationStatus: "conflicting-source",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: null,
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "NEEDS_APPROVAL",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Telesin Digital Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: "https://telesin.en.alibaba.com",
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Telesin-Action-Camera-Accessories-for-Hero_1600937269667.html",
      supplierProductId: "1600937269667",
      supplierYearsActive: 12,
      supplierRating: null,
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "$2.20–$2.50",
      actualOneUnitPrice: null,
      samplePrice: "$1,000 shown on page (treated as erroneous until supplier confirms)",
      currency: "USD",
      moq: 5,
      pricingTiers: [
        { quantity: "5–19 pieces", price: "$2.50" },
        { quantity: "20–99 pieces", price: "$2.40" },
        { quantity: "100–499 pieces", price: "$2.30" },
        { quantity: "500+ pieces", price: "$2.20" },
      ],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Listing shows 5-day dispatch and 7-day lead time for 1–100 pieces; transit is not published.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: ["Listing title includes DJI/Insta360 Ace, but detailed compatibility lists GoPro, SJCAM and Xiaomi Yi only.", "220 sold shown; no product review score shown."],
    })],
    marketComparisons: [{ label: "GoPro Head Strap 2.0", observedPrice: "$26.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: null,
    recommendedRetailPriceUsd: null,
    estimatedProfitUsd: null,
    estimatedMarginPercent: null,
    marginStatus: "NOT_CALCULATED",
    bulkOpportunity: "Do not order bulk until the compatibility conflict and sample-price anomaly are resolved.",
    selectionReason: "The physical design is relevant, but source conflicts correctly keep it out of launch checkout.",
    blockers: ["MOQ 5", "Compatibility conflict", "Sample-price anomaly", shippingRequiresConfirmation, "Reseller image permission", "Physical comfort/retention test"],
  },
  {
    productId: "magnetic-quick-release-base",
    verificationStatus: "source-checked",
    lastVerified: "2026-08-16",
    supplierPriceLastVerified: "2026-08-16",
    shippingLastVerified: null,
    availabilityLastVerified: "2026-08-16",
    // Owner confirmed on 2026-08-16 that the supplier granted photo permission
    // in their Alibaba chat.
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Sturdy-Magnetic-Quick-Release-Base-Compatible_1601859608989.html",
      supplierProductId: "1601859608989",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews; 94.4% on-time dispatch, ≤2h response, 10% reorder rate)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 118.60 (≈US$3.60) at the 10–399 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 169.43 (≈US$5.15)",
      currency: "THB",
      moq: 10,
      pricingTiers: [
        { quantity: "10–399 pieces", price: "THB 118.60 (≈US$3.60)" },
        { quantity: "400–4,999 pieces", price: "THB 110.13 (≈US$3.35)" },
        { quantity: "5,000–9,999 pieces", price: "THB 101.66 (≈US$3.09)" },
        { quantity: "≥10,000 pieces", price: "THB 93.19 (≈US$2.83)" },
      ],
      shippingFinding:
        "Supplier-to-owner shipping showed FREE (capped at THB 677.69 on THB 1,016.54+ orders) with guaranteed delivery Aug 31–Sep 09 quoted to a Thailand address on Aug 16. Outbound shipping to customers is absorbed into the $25 retail price per owner decision, estimated US$4–5 for the 0.15 kg package — not yet measured.",
      deliveryFinding: "Roughly 2–3.5 weeks supplier-to-owner (Aug 31–Sep 09 window quoted Aug 16). 2–5 working day dispatch claimed for normal orders.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Page browsed directly through the owner's signed-in session on 2026-08-16; prices displayed in THB for a Thailand delivery address, USD conversions approximate (~33 THB/USD).",
        "Supplier granted photo usage permission in the owner's Alibaba chat (owner-confirmed 2026-08-16).",
        "New listing: 3 sold, no product reviews yet. The 4.6/5 store rating is dominated by the supplier's watch-strap line, not this product.",
        "Trading company with a claimed Shenzhen factory; brand BEIZIYE, made in Guangdong.",
        "Package 10x10x5 cm, 0.15 kg gross — light enough for inexpensive outbound shipping.",
        "Compatibility (DJI Action 6/6 Pro/5 Pro/4/3, Osmo Nano, Insta360 Ace Pro 2/Ace Pro/X5) is supplier-claimed and not yet physically verified.",
      ],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: 3.6,
    recommendedRetailPriceUsd: 25,
    // 25.00 − 3.60 unit − ~1.05 Stripe − ~4.50 estimated outbound shipping.
    estimatedProfitUsd: 15.85,
    estimatedMarginPercent: 63,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "Tiers fall to ≈US$2.83 at 10,000 pieces; the 10-piece tier is already priced well for launch. Sample ≈US$5.15.",
    selectionReason: "Owner-selected launch product #1: strong margin at the owner-approved $25 price, supplier granted photo rights, and quick-release bases pair naturally with every mount recommendation on the site.",
    blockers: [
      "Physical sample check of magnet strength and claimed camera fit",
      "Outbound US shipping cost is an owner estimate, not yet measured",
      "Stripe is not configured; checkout remains gated",
    ],
  },
  {
    productId: "folding-selfie-tripod",
    verificationStatus: "source-checked",
    lastVerified: "2026-08-16",
    supplierPriceLastVerified: "2026-08-16",
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: "2026-08-16",
    // Same supplier as the magnetic base; owner confirmed photo permission
    // covers their listings (2026-08-16).
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/2-claws-Universal-Selfie-Stick-Foldable_10000041909627.html",
      supplierProductId: "10000041909627",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 144.01 (≈US$4.38) at the 5–499 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 271.08 (≈US$8.24)",
      currency: "THB",
      moq: 5,
      pricingTiers: [
        { quantity: "5–499 pieces", price: "THB 144.01 (≈US$4.38)" },
        { quantity: "500–5,999 pieces", price: "THB 138.93 (≈US$4.22)" },
        { quantity: "6,000–9,999 pieces", price: "THB 133.85 (≈US$4.07)" },
        { quantity: "≥10,000 pieces", price: "THB 130.46 (≈US$3.97)" },
      ],
      shippingFinding: "Supplier-to-owner shipping quoted THB 434.06 (≈US$13.20) for 5 pieces ≈ US$2.64/unit to a Thailand address. Outbound customer shipping absorbed in the $35 retail price per owner decision; 0.11 kg package.",
      deliveryFinding: "Guaranteed delivery Aug 25–Sep 20 quoted Aug 16 (~1.5–5 weeks).",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Browsed through the owner's session 2026-08-16; THB display, ≈33 THB/USD.",
        "14 sold, no product reviews yet; store rating dominated by watch straps.",
        "Extends to 0.4 m, pitch + 180° rotation, soft rubber grip; aluminum alloy + PC; 15x7x4 cm.",
      ],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: 7.02,
    recommendedRetailPriceUsd: 35,
    // 35.00 - 4.38 unit - 2.64 inbound share - ~1.32 Stripe - ~4.50 est. outbound.
    estimatedProfitUsd: 22.16,
    estimatedMarginPercent: 63,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "MOQ 5 with tiers to ≈US$3.97; inbound shipping ≈US$2.64/unit at 5 pieces falls with volume.",
    selectionReason: "Owner-selected launch product #2 at the owner-approved $35 price; complements the site's tripod and selfie-stick recommendations.",
    blockers: [
      "Physical sample check of hinge and claw tolerance",
      "Outbound US shipping cost is an owner estimate, not yet measured",
      "Stripe is not configured; checkout remains gated",
    ],
  },
];

export function getSourcingRecord(productId: string) {
  return accessorySourcingRecords.find((record) => record.productId === productId);
}
