import type { AccessorySourcingRecord, SupplierCandidate } from "./types";

const RESEARCH_DATE = "2026-08-15";
const shippingRequiresConfirmation =
  "Shipping requires confirmation for each destination and one-unit checkout; no universal shipping cost is published.";

const candidate = (value: SupplierCandidate) => value;

export const accessorySourcingRecords: AccessorySourcingRecord[] = [
  {
    productId: "backpack-strap-clip",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Should-Strap-Mount-Quick-Release-Adapter_1601440655582.html",
      supplierProductId: "1601440655582",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 177.90 (~US$5.41) at the 5-299 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 338.85 (~US$10.30)",
      currency: "THB",
      moq: 5,
      pricingTiers: [
        { quantity: "5-299 pieces", price: "THB 177.90 (~US$5.41)" },
        { quantity: "300-1,999 pieces", price: "THB 172.82 (~US$5.25)" },
        { quantity: "2,000-5,999 pieces", price: "THB 169.43 (~US$5.15)" },
        { quantity: "6,000+ pieces", price: "THB 160.96 (~US$4.89)" },
      ],
      shippingFinding: "Supplier-to-owner shipping THB 434.06 (~US$13.20) for 5 pieces, ~US$2.64/unit, to a Thailand address on Aug 16. Outbound customer shipping absorbed in the owner-approved $25 price; 0.07 kg package.",
      deliveryFinding: "Guaranteed delivery Aug 25 - Sep 20 quoted Aug 16.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner waived pre-launch sample testing and outbound-shipping measurement on 2026-08-16, citing full confidence in this supplier. Launched on owner authority without physical verification.",
        "Owner-picked supplier (same company as launch products 1-3); browsed via the owner's session 2026-08-16, THB display ~33 THB/USD.",
        "Photo permission owner-confirmed for this supplier 2026-08-16.",
        "Variant on page: For DJI Osmo Action 3/4/5 Pro anti-slip backpack shoulder-strap bracket; 38 sold, no product reviews yet.",
        "Owner-approved launch price: US$25 (2026-08-16).",
        "13x7x10 cm packaging.",
      ],
    }), candidate({
      role: "alternative",
      supplierName: "Shenzhen Telesin Digital Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Telesin-Universal-Backpack-Clip-for-Go-1600974761579.html",
      supplierProductId: "1600974761579",
      supplierYearsActive: 12,
      supplierRating: "4.9/5.0 (522 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "B/.3.50–B/.4.00",
      actualOneUnitPrice: null,
      samplePrice: "B/.12.90",
      currency: "PAB",
      moq: 10,
      pricingTiers: [
        { quantity: "10–49 units", price: "B/.4.00" },
        { quantity: "50–499 units", price: "B/.3.80" },
        { quantity: "500+ units", price: "B/.3.50" },
      ],
      shippingFinding: shippingRequiresConfirmation,
      deliveryFinding: "Listing shows 8-day lead time for 1–50 units; transit is not published.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: ["Supplier lists max supported camera weight as 250g.", "Materials listed: PC, TPU, carbon steel and 316 stainless steel."],
    })],
    marketComparisons: [{ label: "GoPro Magnetic Swivel Clip", observedPrice: "$34.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: 8.05,
    recommendedRetailPriceUsd: 25,
    estimatedProfitUsd: 11.42,
    estimatedMarginPercent: 46,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "MOQ 10 and a sample price make this a later candidate unless the supplier confirms one-piece fulfillment.",
    selectionReason: "The specified locking clip and multi-material construction better match the quality brief than a bare spring clip.",
    blockers: [],
  },
  {
    productId: "suction-cup-mount",
    verificationStatus: "source-checked",
    lastVerified: RESEARCH_DATE,
    supplierPriceLastVerified: RESEARCH_DATE,
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: RESEARCH_DATE,
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Suction-Cup-Camera-Car-Mount-for_1601905939661.html",
      supplierProductId: "1601905939661",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 237.20 (≈US$7.21) at the 10–199 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 338.85 (≈US$10.30)",
      currency: "THB",
      moq: 10,
      pricingTiers: [
        { quantity: "10–199 pieces", price: "THB 237.20 (≈US$7.21)" },
        { quantity: "200–1,999 pieces", price: "THB 228.72 (≈US$6.95)" },
        { quantity: "2,000–4,999 pieces", price: "THB 220.25 (≈US$6.70)" },
        { quantity: "≥5,000 pieces", price: "THB 211.78 (≈US$6.44)" },
      ],
      shippingFinding: "FREE supplier-to-owner shipping shown (capped THB 677.69 on THB 1,016.54+ orders) to a Thailand address on Aug 16.",
      deliveryFinding: "Guaranteed delivery Aug 25–Sep 20 quoted Aug 16.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner waived pre-launch sample testing and outbound-shipping measurement on 2026-08-16, citing full confidence in this supplier. Launched on owner authority without physical verification.",
        "Owner-picked supplier (same company as launch products #1 and #2); browsed through the owner's session 2026-08-16, THB display ≈33 THB/USD.",
        "Photo permission owner-confirmed for this supplier 2026-08-16.",
        "1/4\"-20 screw mount with 360° rotation and quick release; 15x9x10 cm, 0.16 kg.",
        "No product reviews shown; suction retention on a windshield is the critical physical test before launch.",
        "Owner-approved launch price: US$45 (2026-08-16).",
      ],
    }), candidate({
      role: "alternative",
      supplierName: "Hangzhou Superb Imp. & Exp. Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Action-Camera-Car-Suction-Cup-Mount_1600165629792.html",
      supplierProductId: "1600165629792",
      supplierYearsActive: 9,
      supplierRating: "4.8/5.0 (265 supplier reviews shown)",
      supplierVerified: null,
      tradeAssurance: null,
      displayedPrice: "CA$0.6695–CA$0.7671",
      actualOneUnitPrice: "CA$0.7671 for the 1–9 piece tier",
      samplePrice: null,
      currency: "CAD",
      moq: 1,
      pricingTiers: [
        { quantity: "1–9 pieces", price: "CA$0.7671" },
        { quantity: "10–99 pieces", price: "CA$0.7253" },
        { quantity: "100–999 pieces", price: "CA$0.6974" },
        { quantity: "1,000+ pieces", price: "CA$0.6695" },
      ],
      shippingFinding: "Shipping fee and delivery date are shown as to be negotiated.",
      deliveryFinding: "Transit time requires supplier confirmation.",
      dropshippingSupported: null,
      sampleSupported: null,
      trackingAvailable: null,
      sourceNotes: ["Listing states ABS/silicone construction, 70g weight and a one-year warranty.", "The price is unusually low; launch requires a physical suction and retention test."],
    })],
    marketComparisons: [{ label: "GoPro Suction Cup", observedPrice: "$39.99 regular", sourceUrl: "https://gopro.com/en/af/shop/mounts-accessories/camera-mounts", checkedAt: RESEARCH_DATE }],
    estimatedLandedCostUsd: 7.21,
    recommendedRetailPriceUsd: 45,
    estimatedProfitUsd: 31.18,
    estimatedMarginPercent: 69,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "MOQ 1 is suitable for a sample; do not bulk-buy a safety-critical suction product before testing.",
    selectionReason: "One-piece tier, stated material and warranty make it researchable, but not yet safe to sell without a test.",
    blockers: [],
  },
  {
    productId: "magnetic-quick-release-base",
    verificationStatus: "source-checked",
    lastVerified: "2026-08-16",
    supplierPriceLastVerified: "2026-08-16",
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: "2026-08-16",
    // Owner confirmed on 2026-08-16 that the supplier granted photo permission
    // in their Alibaba chat.
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Sturdy-Magnetic-Quick-Release-Base-Compatible_1601859608989.html",
      supplierProductId: "1601859608989",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews; 94.4% on-time dispatch, ≤2h response, 10% reorder rate)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 118.60 (≈US$3.60) at the 10–399 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 169.43 (≈US$5.15)",
      currency: "THB",
      moq: 10,
      pricingTiers: [
        { quantity: "10–399 pieces", price: "THB 118.60 (≈US$3.60)" },
        { quantity: "400–4,999 pieces", price: "THB 110.13 (≈US$3.35)" },
        { quantity: "5,000–9,999 pieces", price: "THB 101.66 (≈US$3.09)" },
        { quantity: "≥10,000 pieces", price: "THB 93.19 (≈US$2.83)" },
      ],
      shippingFinding:
        "Supplier-to-owner shipping showed FREE (capped at THB 677.69 on THB 1,016.54+ orders) with guaranteed delivery Aug 31–Sep 09 quoted to a Thailand address on Aug 16. Outbound shipping to customers is absorbed into the $25 retail price per owner decision, estimated US$4–5 for the 0.15 kg package — not yet measured.",
      deliveryFinding: "Roughly 2–3.5 weeks supplier-to-owner (Aug 31–Sep 09 window quoted Aug 16). 2–5 working day dispatch claimed for normal orders.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner waived pre-launch sample testing and outbound-shipping measurement on 2026-08-16, citing full confidence in this supplier. Launched on owner authority without physical verification.",
        "Page browsed directly through the owner's signed-in session on 2026-08-16; prices displayed in THB for a Thailand delivery address, USD conversions approximate (~33 THB/USD).",
        "Supplier granted photo usage permission in the owner's Alibaba chat (owner-confirmed 2026-08-16).",
        "New listing: 3 sold, no product reviews yet. The 4.6/5 store rating is dominated by the supplier's watch-strap line, not this product.",
        "Trading company with a claimed Shenzhen factory; brand BEIZIYE, made in Guangdong.",
        "Package 10x10x5 cm, 0.15 kg gross — light enough for inexpensive outbound shipping.",
        "Compatibility (DJI Action 6/6 Pro/5 Pro/4/3, Osmo Nano, Insta360 Ace Pro 2/Ace Pro/X5) is supplier-claimed and not yet physically verified.",
      ],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: 3.6,
    recommendedRetailPriceUsd: 25,
    // 25.00 − 3.60 unit − ~1.05 Stripe − ~4.50 estimated outbound shipping.
    estimatedProfitUsd: 15.85,
    estimatedMarginPercent: 63,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "Tiers fall to ≈US$2.83 at 10,000 pieces; the 10-piece tier is already priced well for launch. Sample ≈US$5.15.",
    selectionReason: "Owner-selected launch product #1: strong margin at the owner-approved $25 price, supplier granted photo rights, and quick-release bases pair naturally with every mount recommendation on the site.",
    blockers: [],
  },
  {
    productId: "folding-selfie-tripod",
    verificationStatus: "source-checked",
    lastVerified: "2026-08-16",
    supplierPriceLastVerified: "2026-08-16",
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: "2026-08-16",
    // Same supplier as the magnetic base; owner confirmed photo permission
    // covers their listings (2026-08-16).
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/2-claws-Universal-Selfie-Stick-Foldable_10000041909627.html",
      supplierProductId: "10000041909627",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 144.01 (≈US$4.38) at the 5–499 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 271.08 (≈US$8.24)",
      currency: "THB",
      moq: 5,
      pricingTiers: [
        { quantity: "5–499 pieces", price: "THB 144.01 (≈US$4.38)" },
        { quantity: "500–5,999 pieces", price: "THB 138.93 (≈US$4.22)" },
        { quantity: "6,000–9,999 pieces", price: "THB 133.85 (≈US$4.07)" },
        { quantity: "≥10,000 pieces", price: "THB 130.46 (≈US$3.97)" },
      ],
      shippingFinding: "Supplier-to-owner shipping quoted THB 434.06 (≈US$13.20) for 5 pieces ≈ US$2.64/unit to a Thailand address. Outbound customer shipping absorbed in the $35 retail price per owner decision; 0.11 kg package.",
      deliveryFinding: "Guaranteed delivery Aug 25–Sep 20 quoted Aug 16 (~1.5–5 weeks).",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner waived pre-launch sample testing and outbound-shipping measurement on 2026-08-16, citing full confidence in this supplier. Launched on owner authority without physical verification.",
        "Browsed through the owner's session 2026-08-16; THB display, ≈33 THB/USD.",
        "14 sold, no product reviews yet; store rating dominated by watch straps.",
        "Extends to 0.4 m, pitch + 180° rotation, soft rubber grip; aluminum alloy + PC; 15x7x4 cm.",
      ],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: 7.02,
    recommendedRetailPriceUsd: 35,
    // 35.00 - 4.38 unit - 2.64 inbound share - ~1.32 Stripe - ~4.50 est. outbound.
    estimatedProfitUsd: 22.16,
    estimatedMarginPercent: 63,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "MOQ 5 with tiers to ≈US$3.97; inbound shipping ≈US$2.64/unit at 5 pieces falls with volume.",
    selectionReason: "Owner-selected launch product #2 at the owner-approved $35 price; complements the site's tripod and selfie-stick recommendations.",
    blockers: [],
  },
  {
    productId: "pocket-lens-cover",
    verificationStatus: "source-checked",
    lastVerified: "2026-08-16",
    supplierPriceLastVerified: "2026-08-16",
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: "2026-08-16",
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Lens-Cover-Protector-for-DJI-OSMO_1601904215095.html",
      supplierProductId: "1601904215095",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 194.84 (~US$5.93) at the 10-399 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 271.08 (~US$8.24)",
      currency: "THB",
      moq: 10,
      pricingTiers: [
        { quantity: "10-399 pieces", price: "THB 194.84 (~US$5.93)" },
        { quantity: "400-4,999 pieces", price: "THB 186.37 (~US$5.67)" },
        { quantity: "5,000-9,999 pieces", price: "THB 177.90 (~US$5.41)" },
        { quantity: "10,000+ pieces", price: "THB 169.43 (~US$5.15)" },
      ],
      shippingFinding: "FREE supplier-to-owner shipping shown to a Thailand address on Aug 16. Outbound customer shipping absorbed in the owner-approved $35 price; 0.14 kg package.",
      deliveryFinding: "Guaranteed delivery Aug 25 - Sep 20 quoted Aug 16.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner waived pre-launch sample testing and outbound-shipping measurement on 2026-08-16, citing full confidence in this supplier. Launched on owner authority without physical verification.",
        "Owner-picked supplier (same company as products 1-4); browsed via the owner's session 2026-08-16, THB display ~33 THB/USD.",
        "Photo permission owner-confirmed for this supplier 2026-08-16.",
        "Page variant: For DJI Pocket 4P flip cover protecting lens and screen; no product reviews yet; 18x5x5 cm.",
        "Owner-approved launch price: US$35 (2026-08-16).",
      ],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: 5.93,
    recommendedRetailPriceUsd: 35,
    estimatedProfitUsd: 23.25,
    estimatedMarginPercent: 66,
    marginStatus: "GOOD_MARGIN",
    bulkOpportunity: "Tiers to ~US$5.15 at 10k; MOQ 10 with free inbound shipping.",
    selectionReason: "Owner-selected launch product #5 at the owner-approved $35 price.",
    blockers: [],
  },
  {
    productId: "wrist-lanyard",
    verificationStatus: "source-checked",
    lastVerified: "2026-08-16",
    supplierPriceLastVerified: "2026-08-16",
    shippingLastVerified: "2026-08-16",
    availabilityLastVerified: "2026-08-16",
    imageUsageStatus: "APPROVED_FOR_USE",
    candidates: [candidate({
      role: "primary",
      supplierName: "Shenzhen Little Wolf Trading Co., Ltd.",
      supplierCountry: "China",
      supplierUrl: null,
      alibabaProductUrl: "https://www.alibaba.com/product-detail/Adjustable-Lanyard-Wristband-for-Selfie-Tripod_1601874979241.html",
      supplierProductId: "1601874979241",
      supplierYearsActive: 5,
      supplierRating: "4.6/5 store rating (1,404 store reviews)",
      supplierVerified: null,
      tradeAssurance: true,
      displayedPrice: "THB 32.20 (~US$0.98) at the 10-499 piece tier",
      actualOneUnitPrice: null,
      samplePrice: "THB 84.72 (~US$2.58)",
      currency: "THB",
      moq: 10,
      pricingTiers: [
        { quantity: "10-499 pieces", price: "THB 32.20 (~US$0.98)" },
        { quantity: "500-4,999 pieces", price: "THB 29.48 (~US$0.90)" },
        { quantity: "5,000-9,999 pieces", price: "THB 28.81 (~US$0.88)" },
        { quantity: "10,000+ pieces", price: "THB 27.11 (~US$0.82)" },
      ],
      shippingFinding: "Supplier-to-owner shipping THB 377.14 (~US$11.47) for 10 pieces, ~US$1.15/unit, to a Thailand address on Aug 16. Outbound customer shipping absorbed in the owner-approved $10 price; 0.03 kg package.",
      deliveryFinding: "Guaranteed delivery Aug 25 - Sep 20 quoted Aug 16.",
      dropshippingSupported: null,
      sampleSupported: true,
      trackingAvailable: null,
      sourceNotes: [
        "Owner waived pre-launch sample testing and outbound-shipping measurement on 2026-08-16, citing full confidence in this supplier. Launched on owner authority without physical verification.",
        "Owner-picked supplier (same company as products 1-5); browsed via the owner's session 2026-08-16, THB display ~33 THB/USD.",
        "Photo permission owner-confirmed for this supplier 2026-08-16.",
        "No product reviews yet; 10x4x3 cm, 0.03 kg.",
        "Owner-approved launch price: US$10 (2026-08-16). Thin absolute profit - strongest as an add-on/bundle item alongside a mount order.",
      ],
    })],
    marketComparisons: [],
    estimatedLandedCostUsd: 2.13,
    recommendedRetailPriceUsd: 10,
    estimatedProfitUsd: 3.28,
    estimatedMarginPercent: 33,
    marginStatus: "ACCEPTABLE_MARGIN",
    bulkOpportunity: "Unit cost under US$1; a natural freebie or bundle line once volume exists.",
    selectionReason: "Owner-selected launch product #6 at the owner-approved $10 price; pairs with every handheld and stick recommendation.",
    blockers: [],
  },
];

export function getSourcingRecord(productId: string) {
  return accessorySourcingRecords.find((record) => record.productId === productId);
}
